### ISSUE TITLE
Create the Figma Design.

### ISSUE THREAD

**Issue by FarahZaqout** [fack2/attention-training#1]
### Pages:
 * [ ] Landing page / quiz (point-based system
    * H1 -> What’s your ADHD superpower?
    * Two lines of context info
    * Scroll through questions (Dice.Fm mobile app, typeform)
    * [Form Inspiration](https://www.typeform.com/#examples)
    * [Question List](https://add.org/wp-content/uploads/2015/03/adhd-questionnaire-ASRS111.pdf)
    * Progress bar
    * Potential for smooth scroll to next question, when user has selected an answer
    * Submit button
 * [ ] Results page
    * What form of ADHD a person exhibits most
    * Submit button
 * [ ] Dashboard
    * Link to Results (come in 4 different flavours - inattentiveness, hyperactivity, both, none)
    * Retake the test
    * COPY: Link: Use your superpowers (feedback loop)
    * Your potential super power (hyper creativity, hyper focussed, hyper sensitivity)
        * Description
        * “Discover your triggers/patterns”
        * Build feedback loops
    * COPY: Link: I’m in trouble
        * Short term solutions:
          * COPY: Having trouble getting started with a project I need to get finished
          * COPY: Having trouble completing something and putting it out there
          * COPY: Caught in a hyperfocussed binge.

### Inspiration:
* The mobile version of [dice.fm](https://dice.fm/).
* [Type Form](https://www.typeform.com) for the form design.
* [Links with cool animations from Yousef](https://docs.google.com/document/d/1Pp6hk3chloG5gQkGJXgFmpLQwl74hJKxEhglhORIGok/edit?usp=sharing)

**Comment by FarahZaqout** [comment]
Add a link to the figma design in the issue.

**Comment by saharAdem** [comment]
[Figma design](https://www.figma.com/file/yO9jtqNG1qcrUFb0kAdQfu/Attention-Training?node-id=0%3A1)
