### ISSUE TITLE
individualSkill-page

### ISSUE THREAD

**Issue by saharAdem** [fack2/attention-training#10]
As a user, I should be able to get information about how to improve my individual skills.

<p align="center">
<img src="https://user-images.githubusercontent.com/41991629/66127211-d8493200-e5f3-11e9-92e2-b4290e77c39f.png" width="200"  height="610"/>
</p>

### Acceptance criteria:
- [ ] image
- [ ] title and description
- [ ] dashboard button. 
- [ ] back button

**Comment by YousefQwasmeh** [comment]
- pressed on dashboard button    /dashboard
- back button calls                        /skills

**Comment by teenie-quaggard** [comment]
## For Superpower article "Hyper focus", see #32

**Comment by teenie-quaggard** [comment]
## For Everyday article "Pomodoros", see #32

**Comment by FarahZaqout** [comment]
@Nadeen123 https://www.npmjs.com/package/html-to-react
Use this to inject html text safely into react code.
you can add the tags u need into the string and it will map it to react elements and render it.
Follow the example marked as ```simple```
