### ISSUE TITLE
AboutUs-page

### ISSUE THREAD

**Issue by YousefQwasmeh** [fack2/attention-training#12]
- As a user, I should be able to see description about the website.
- As a user, I should be able to press a back button to go back to the previous page.

<p align="center">
<img src="https://user-images.githubusercontent.com/48014915/66127879-61149d80-e5f5-11e9-8a90-61bfab8b2902.png" width="200" height="350" />
</p>

### Acceptance criteria:
- [x] title
- [x] description
- [x]  back button

**Comment by Nadeen123** [comment]
* back button calls ```/dashboard```

**Comment by teenie-quaggard** [comment]
Copy has been noted in #32
