### ISSUE TITLE
InitialQuiz-page

### ISSUE THREAD

**Issue by Nadeen123** [fack2/attention-training#3]
As a user, I should be able to click a card to start the test.

<p align="center">
<img width="200" height="350" alt="Initial quiz page" src="https://user-images.githubusercontent.com/41991629/66265893-5ab93800-e826-11e9-9da1-2e138071bb11.png"> 
</p>

### Acceptance criteria:
- [x] card
- [x] skip button
- [x] progress bar

**Comment by FarahZaqout** [comment]
endpoint: ```/quiz-instructions```
This view is the final of a sequence of instructions that use the same component, and dynamically change the text.

final view calls: ```/quiz```
