### ISSUE TITLE
Quiz-page

### ISSUE THREAD

**Issue by Nadeen123** [fack2/attention-training#4]
- As a user, I should be able to see a card contain a question and click on the answer button.
 - As a user, I should be able to exit the test by click the (X) button.
 - As a user, I should be able to back to the previous question by clicking the (←) back button.

<p align="center">
<img src="https://user-images.githubusercontent.com/48320569/66266724-7c6bec80-e831-11e9-8cf8-44b6cf597caa.png " width="200" height="350" >
</p>

### Acceptance criteria:
- [ ] question card
- [ ] answer buttons
- [ ] X button
- [ ] progress bar
- [ ]  (←) back button

### * X button shows a pop-up modal
- As a user, If I press ok button I'll lose my test progress and go to dashboard.
- As a user, If I press cancel button I'll stay in test.
<p align="center">
<img src="https://user-images.githubusercontent.com/48320569/66266739-a9200400-e831-11e9-9fac-e58f93c69d50.png " width="200" height="200" >
</p>

### Acceptance criteria:
- [ ] ok button
- [ ] cancel button

**Comment by Nadeen123** [comment]
* back button call ```\quiz```
* x button call ```\dashborad```
* ok button call ```\dashborad```

**Comment by FarahZaqout** [comment]
We could potentially animate the cards movement in a similar way to typeform.

**Comment by teenie-quaggard** [comment]
**For quiz questions please see #32**

**Comment by FarahZaqout** [comment]
Re-opened the issue because we didn't do the modal for closing the test before finishing it.
