### ISSUE TITLE
50%Progress-page

### ISSUE THREAD

**Issue by Nadeen123** [fack2/attention-training#5]
- As a user, I should be able to see 50% progress bar, descreption if I finished half of questions. 
-  As a user, I should be able to press a keep going button to continue the test.
- As a user, I should be able to press a back button to go back to the previous page.
<p align="center">
<img src="https://user-images.githubusercontent.com/48320569/66123186-180b1c00-e5ea-11e9-8bc6-0e3a08bcfdb7.png " width="200" height="350" >
</p>

### Acceptance criteria:
- [ ] 50% progress bar
- [ ] descreption
- [ ] keep going button
- [ ] back button

**Comment by saharAdem** [comment]
endpoint is /quiz
