### ISSUE TITLE
100%Progress-page

### ISSUE THREAD

**Issue by Nadeen123** [fack2/attention-training#6]
- As a user, I should be able to see a 100% progress bar, description if I finished the questions. 
- As a user, I should be able to click see result button to go to the result page.
 
<p align="center">
<img src="https://user-images.githubusercontent.com/48320569/66265978-84bf2a00-e827-11e9-8127-81fc65fdd2ff.png " width="200" height="350" >
</p>

### Acceptance criteria:
- [ ] 100% progress bar
- [ ] descreption
- [ ] see result button

**Comment by saharAdem** [comment]
- see results buttons calls /result
