### ISSUE TITLE
Results-page

### ISSUE THREAD

**Issue by Nadeen123** [fack2/attention-training#7]
- As a user, I should be able to see a descreption about my ADHD type.
- As a user, I should be able to press a dashboard button to go to the dashboard page.
<p align="center">
<img src="https://user-images.githubusercontent.com/48320569/66124184-6ae5d300-e5ec-11e9-8eb1-f99a393c04e7.png " width="200" height="400" >
</p>

### Acceptance criteria:
- [ ] description about ADHD type
- [ ] dashboard button

**Comment by saharAdem** [comment]
- dashboard button calls /dashboard

**Comment by teenie-quaggard** [comment]
## For results copy, see #32
