### ISSUE TITLE
Skills-pages

### ISSUE THREAD

**Issue by Nadeen123** [fack2/attention-training#8]
- As a user, I should be able to see cards and click the card to go to the skill details page. 
-  As a user, I should be able to filter the skills cards to everyday and superpower skills.
- As a user, I should be able to press a back button to go back to the previous page.

<p align="center">
<img src="https://user-images.githubusercontent.com/48320569/66124967-71754a00-e5ee-11e9-8ed7-e76898f5f347.png " width="150" height="350" >
</p>

### Acceptance criteria:
- [ ] filter
- [ ] cards
    - [ ] image
    - [ ] title
- [ ]  back button

**Comment by YousefQwasmeh** [comment]
- pressed on card    /skills/:id
- back button calls   /dashboard
